### ISSUE TITLE
Parameter format waktu pada endpoint /tambahjadwal

### ISSUE THREAD

**Issue by naufalpf** [2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-ichsan-arya-adam#1]
Pada endpoint `/tambahjadwal` , untuk parameter *jammasuk* dan *jamselesai* format waktunya belum jelas.
Mohon diberikan contohnya

**Comment by ichsanSandi** [comment]
Format inputan waktu pada `/tambahjadwal` adalah YYYY-MM-DDThh:mm:ss
Sebagai contoh, mata kuliah X ingin menambah jadwal pada hari Selasa tanggal 14 Mei 2019 pada jam 10 pagi sampai 12 siang. Maka input jamMasuk berupa 2019-05-14T10:00:00, dan jamSelesai berupa 2019-05-14T12:00:00. Closed https://github.com/2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-ichsan-arya-adam/commit/33a71194f221f6e494050e6ca7aa362e9766ba92

**Comment by naufalpf** [comment]
Baik, terima kasih atas penjelasannya
