### ISSUE TITLE
Tipe data nrp

### ISSUE THREAD

**Issue by naufalpf** [2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-ichsan-arya-adam#2]
tipe data `userRegisterNumber`/`nrp` ialah  *Number* sehingga saat memasukkan NRP 05111540000057, 0 di awal akan hilang. Sebaiknya diganti `string` saja, terima kasih.

**Comment by aryarino** [comment]
Hi @naufalpf ,
Terima kasih atas sarannya. Untuk tipe data `userRegisterNumber` sudah diubah menjadi _String_ di commit terbaru kami (251c045b1f773a17965a6e7d66a52b5cc965ff90)

**Comment by naufalpf** [comment]
Halo @arya1998,
terima kasih sudah memperbaikinya
